### ISSUE TITLE
Download folder add's to rather than replaces aria2 configuration default

### ISSUE THREAD

**Issue by gbcox** [jc3213/download_with_aria2-firefox#10]
My aria2 default download folder is:  /vault/downloads/folder.  If I specify use the default, it downloads to /vault/downloads/folder/vault/downloads/folder.   If I specify use browser, and in the browser I direct to /home/download it sends the files to /vault/downloads/folder/home/download.  You should be replacing rather than appending the target directory specified.  Other than that, so far so good.  Your extension is working as expected where other aria2 extensions have failed.

**Comment by jc3213** [comment]
Sorry, but I wonder if you are using Linux OS? It works fine on windows version of Firefox.

Besides, it is recommended that you'd better use `absolute path` rather than `relative path`. aria2 does treat relative path as expansion of your default aria2 download folder.

In https://github.com/jc3213/download_with_aria2-firefox/blob/4fccf74aa74aa65c67d371943c12dd887064e751/components/common.js#L80
If you set download folder to `Browser` (value = 1), it will extract file path from file full path, since firefox downloadItem.filename provides full path. in Windows, you can get `D:\Downloads` or something else

In https://github.com/jc3213/download_with_aria2-firefox/blob/4fccf74aa74aa65c67d371943c12dd887064e751/components/common.js#L83
If you set download folder to `Custom` (value = 2), if will read the value you set, in Windows probably `D:\Aria2 Downloads`

If you set download folder to `Default` (value = 0), the procession won't provide `out` option to define output folder of aria2 downloads.

I don't quite know how it works on Linux though. I have no environment to test it.

**Comment by gbcox** [comment]
Yes, I'm using Linux - and I'm using absolute paths.
This is a Fx extension, so the assumption is and should be that it is used from Fx.
Fx has 2 settings for downloads in the preferences  
1.  Save files to:  (Which sets the default location for all Fx Downloads)
2.  Choose location (Always ask where to save your files)

In addition, aria2 has a default location you can specify in your aria2.conf
The keyword here being default, which means that is where the files will be downloaded unless another location is chosen

Your extension has 3 options. 

Let's discuss option 1, Default.  As I understand it, you're saying that if you choose option 1, then the file will be downloaded to what is specified in your aria2.conf for default location.

In my instance the location is set to:  /home/user/downloads
Fx has a default location set as: /home/user/downloads

When I download a file using Default, the file is downloaded to:  /home/user/downloads/home/user/downloads
If I choose option 2 browser, the file is downloaded to: /home/user/downloads/home/user/downloads

The only way I can get this to work is to use the Custom option and simply specify the root directory:  /

Then things work as expected.  

As I mentioned above, yours is the first Fx aria2 extension that seems to work so far with all websites.  I've yet to encounter an issue - however, with download location, not so much, although the "custom" is a good circumvention if you can't figure it out.

The other extensions out there are handling this correctly.  You might take a look for a clue as to what is happening.

But again, good job on compatibility with websites!

**Comment by jc3213** [comment]
>In my instance the location is set to: /home/user/downloads
>Fx has a default location set as: /home/user/downloads
>
>When I download a file using Default, the file is downloaded to: /home/user/downloads/home/user/downloads
>If I choose option 2 browser, the file is downloaded to: /home/user/downloads/home/user/downloads

That's strange, since if you set that to `Default`, no `dir`  option will be passed to Aria2 RPC (you can also try that in console), then Aria2 should save files to where you defined in `aria2.conf`

I wonder if you can run the extension debug, run ```downWithAria2({url: 'https://github.com/jc3213/download_with_aria2-firefox/archive/master.zip', referer: 'https://github.com/jc3213/download_with_aria2-firefox', domain: 'github.com'})```

Please let me know the result

**Comment by gbcox** [comment]
Sorry, but I know basically nothing about Fx extensions.  Can you give me idiot proof instructions on how to gather this information and I'll be happy to send you the output.

**Comment by jc3213** [comment]
1) You need to download `Developer` version of Firefox
2) Download extension source code, add ```console.log(json)``` to where I've mentioned in https://github.com/jc3213/download_with_aria2-firefox/issues/10#issuecomment-745061263
3) Pack the source code into `.zip`, rename `.zip` to `.xpi` (or you pack `.zip` just name it as `xxxx.xpi`)
4) Open Firefox `about:config`, change `xpinstall.signatures.required` to `false`
5) Install the packed extension, open `Extension Manager`, Click `⚙`, choose `Debug Add-ons xxxxx` (I can't remember the menu)
6) Click `Inspect` on `Download with Aria2` on the extension debugging page
7) Click `Console`
8) Download `Something` then choose the log which contains `method: aria2.addUri` (as my screenshot)
9) Provide 3 screenshots for 3 different option settings if possible

**Comment by gbcox** [comment]
Hi, thanks for the instructions!  I did the tests and attached a few screenshots.  I now understand what is happening, and it was a bit confusing to me, but is perfectly correct.  

It depends upon how one has configured their aria2 server.  My server has a default directory defined in the configuration.  As per the [documentation](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-o ), if you define a target directory then the filename of the download file is always relative to the directory defined in the configuration.  You had mentioned this earlier, but I didn't make that connection.  When I specify custom as "/" that then effectively overrides my aria2 config setting and allows me place the file according to what I specify in the Fx "save as" dialog.   

The reason it is confusing is if you have something set in the aria2 configuration for the default directory, that is not reflected in the Fx "save as" dialog.  For example, if you have "/vault/staging" as the default directory of aria2, that is then locked in as the relative base.  Then if you use either "default" or "browser" and decided to use the Fx "save as" dialog, and then choose the file destination directory as say "/home/user/files", then the file will be placed in "/vault/staging/home/user/files".  

The way to avoid this with the "default or browser" settings would be to not have a default destination defined in your aria2 config - OR - just always use the "custom" setting and have it set as "/".

It's not wrong, it's working as designed - but at least on Linux, it can be confusing, mainly because of the way the Fx "save as" dialog works.  Since your extension integrates so nicely with the Fx downloading dialog it might be easier to have it default to "custom" with a default of "/" and let people put their default information in the Fx  download preferences.  

![image](https://user-images.githubusercontent.com/4543019/102395566-2bf13280-3f90-11eb-82cf-053878ac94cb.png)
![image](https://user-images.githubusercontent.com/4543019/102395761-6d81dd80-3f90-11eb-95bd-c2c0b6559de8.png)

**Comment by jc3213** [comment]
I've got what's the problem, it is because I use `regexp` to match `X:\yyyy\zzzz\aaaa.zip` to get `aaaa.zip` directory format, that works on Windows, but not work as expected on Linux. Since where Firefox `downloadItem.filename` always provide full file path not only filename as Chromium does. and the file path format on Windows is different compare to Linux.

You got file download in expanded path that is because you have `"out": "/xxx/yyy/zzzz/aaaa.zip"` option, thus, which provides duplicated relative file path `/xxx/yyy/zzz/`, so if your Aria2 is set to download in `/home/user`, the result will be `/home/user/xxx/yyy/zzz`.

A patch will be filed, but it will take some time for me to get a better way to extract the file name and file path for both Windows and Linux, And for now, as a work around, use `Custom` and `/` will be the best choice.

**Comment by gbcox** [comment]
I tested and it now works perfect, exactly as I would expect.  Thanks again for the quick response!
