### ISSUE TITLE
Last few releases, downloads fail

### ISSUE THREAD

**Issue by gbcox** [jc3213/download_with_aria2-firefox#26]
Last few releases, including current 2.7020 receive message "Download aborted".  Not sure what you changed, but it isn't working.  Last release you loaded to AMO before you started having upload issues appears to be working fine.

**Comment by jc3213** [comment]
oops, I've tested in a clean profile and everything works fine for me though. I know that problem is caused by changes to the `storage`, it has been mentioned here https://github.com/jc3213/download_with_aria2-firefox/issues/25#issuecomment-869167880
```json
{
    jsonrpc: {
        token: 'token:'
    },
}
```

The temprory work around is clear all storage then import the default one, so I've implement that. If you have updated to 2.7020, your settings should have been cleared.

PS: The previous compatibility code in 2.7010 seems not work and has been replaced to this one, https://github.com/jc3213/download_with_aria2-firefox/commit/c8c42c080b6f7d5a00142e3f5aa69337d1aec2c8#diff-bb06783fccd762e4d905ab922491e954a9fbaf708a1acbf53dff92872b0bcd3bL114

**Comment by gbcox** [comment]
Hi, yes I am using 2.7020 that was uploaded by ivysrono.  I tried stopping and starting the extension multiple times and starting and stopping firefox only, but keep getting the aborted messages everytime I try to download anything.  As I mentioned, the old version still works fine, it is the new versions which aren't working.

**Comment by jc3213** [comment]
Can you open debug console and input `aria2RPC` and tell me the result?

![aria2RPC](https://user-images.githubusercontent.com/8744936/123648807-d6a9ae00-d85b-11eb-8ee9-a23d6331c5c2.png)

**Comment by jc3213** [comment]
I've tried again a new profile and installed 2.6610, the last version of old logic and structure, and then updated to 2.7020.

Notification shows, and tells me `Unauthorized` since no `token` is set. I've input my token, then it works properly.

**Comment by gbcox** [comment]
OK, what I had to do was to completely delete the extension, restart firefox and re-install it again.  Now it can download ONLY if I say to ALWAYS download in the settings.  If I try to use the built-in filters to match on filetype, it no longer works.

**Comment by jc3213** [comment]
I wonder the version of your firefox? I'm been testing in `85.0b2` development build

**Comment by jc3213** [comment]
Yet, another issue found during tests that was related to `Download Folder` > `Browser` setting, and had been fixed in https://github.com/jc3213/download_with_aria2-firefox/commit/1e44f905d20987f025d3323df66642e239366a0b

**Comment by jc3213** [comment]
Since 2.6700, the work stream is `aria2c.exe` <=> `background.js` <=> `other modules`, the older version are `aria2c.exe` <=> `background.js` and `other modules`. and `aria2RPC` is what has been sent from `background.js` to `other modules`

`background.js` retrieve all imformations from `aria2c.exe` every 1 second. then sending message every 2 seconds. This is based on your setting, min 1, max 10 in `options`

I've switched to `connect` API in 2.7110 to solve the error logs in `background.js` about posting message via disconnected port. But I got another problem on updating `Refresh Interval` settings in realtime, although you can reopen the `popup` page to take effect

**Comment by jc3213** [comment]
Can you help me test new code on Linux? 
[Firefox-3.0.0.zip](https://github.com/jc3213/download_with_aria2-archived/files/7193640/Firefox-3.0.0.zip)
https://github.com/jc3213/download_with_aria2/commit/5a763161c5f128169190560601d0c7a4ff568572
