### ISSUE TITLE
Pass file name to aria2

### ISSUE THREAD

**Issue by CrendKing** [jc3213/download_with_aria2-firefox#3]
I use capture and sometimes aria2 would save to a file (mostly "index.html") with a different name than what Firefox showed in the popup. I think it is because currently only the path part of the `filename` field is passed. Can you also extract the basename and pass to aria2?

**Comment by jc3213** [comment]
hmm，this should be firefox exclusive either, as part of `Download Folder` option, I'll look into this

**Comment by CrendKing** [comment]
Thank you! I don't see how the whole download folder feature can't be available on the Chromium version, as they have the similar API. But you are the boss :)

**Comment by jc3213** [comment]
Chrome triggers `onDeterminingFilename` after popup for saving files, but won't let you choose the folder.While Firefox let you choose where to save the files. Thus, `filename` property only gives you the name of the file not the full path.

That's why I said this should be Firefox exclusive. they both popup to ask you `Save, Save As, Open, Cancel`, but don't work the same

**Comment by CrendKing** [comment]
But if Chromium does pass you the name of the file, can't you pass that name to aria2? I know the `dir` is not there, but at least `out` is there, better than nothing. Could be useful if user decides to save to a different name.

We could move the discussion to the chromium side if you prefer.

**Comment by jc3213** [comment]
You click `Save` or `Save As` or `Open`, else of `Cancel`. The download sequence is intercepted by `onDeterminingFilename` event on Chromium. But if you click `Save` on Firefox, it will prompt another window that ask you to change the folder to save or the filename itself.

Since filename can't be changed, there's no need for `filename` property for `out` option

**Comment by CrendKing** [comment]
Sorry I didn't realize the Chromium version intercepts at the earlier event. Is there a reason why it's done at `onDeterminingFilename` instead of `onCreated`?

**Comment by jc3213** [comment]
I don't know... The process of downloads is =>
1) You click on url or `Save as`, Chrome triggers `onCreated` event before any prompt is shown `filename` property is `""` (aka empty). `url` is sometime the same as `finalUrl` (affect some downloads with redirections)
2) Promt to ask you `Save`, `Cancel`(Firefox), `Save`, `Save As`, `Open`, `Cancel` (Chrome)
3) Chrome triggers `onDeterminingFilename` event
4) Promt to ask you where to download, and filename
5) Firefox triggers `onCreated` event, with bug `fileSize` property `-1`(aka unknown)

It will be easy to full `filename` to check for capture. Otherwise, some file hosts don't provide proper `finalUrl` on `onCreated` event. While `filename` is `""`, and you can't get full filename from the `finalUrl`, there's no way to check for file extensions
